apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: baseball
spec:
  selector:
    app: flask-app
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
