name: Deploy Flask App to AKS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        run: |
          az acr login --name baseballacr
          docker build -t baseballacr.azurecr.io/flask-app:latest .
          docker push baseballacr.azurecr.io/flask-app:latest

      - name: Set up Kubernetes
        run: |
          az aks get-credentials --resource-group my-aks-rg --name my-aks-cluster

      - name: Apply Kubernetes Configuration
        run: |
          kubectl apply -f k8s/namespace.yaml
          kubectl apply -f k8s/deployment.yaml --namespace=baseball
          kubectl apply -f k8s/service.yaml --namespace=baseball
          kubectl apply -f k8s/hpa.yaml --namespace=baseball
